name: Notify

on:
  push:
    branches: [ preview, release ]

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Notify theme updates
        run: |
          curl --fail --request GET --header "Authorization: Bearer $SIGN" --url "https://dev.biji.io/actions?url=https://github.com/Tokinx/Wing/archive/refs/heads/main.zip"
        env:
          SIGN: ${{ secrets.SIGN }}
